"""add patient table

Revision ID: 6bb0cff00202
Revises: 8f4b2a9e1d3c
Create Date: 2026-07-22 16:53:52.103389

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6bb0cff00202"
down_revision: str | None = "8f4b2a9e1d3c"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    clinic_plan_tier = sa.Enum("free", "practice", "clinical_pro", name="clinic_plan_tier")
    clinic_plan_tier.create(op.get_bind(), checkfirst=True)

    op.add_column("clinics", sa.Column("branding_logo_url", sa.String(length=2048), nullable=True))
    op.add_column("clinics", sa.Column("branding_color", sa.String(length=32), nullable=True))
    op.add_column("clinics", sa.Column("plan_tier", clinic_plan_tier, nullable=False))
    op.add_column("clinics", sa.Column("is_partner_clinic", sa.Boolean(), nullable=False))
    op.drop_index(op.f("ix_clinics_status"), table_name="clinics")
    op.create_index("ix_clinics_plan_tier", "clinics", ["plan_tier"], unique=False)
    op.drop_column("clinics", "state")
    op.drop_column("clinics", "postal_code")
    op.drop_column("clinics", "address")
    op.drop_column("clinics", "city")
    op.drop_column("clinics", "country")
    op.drop_column("clinics", "phone")
    op.drop_column("clinics", "status")
    op.drop_column("clinics", "email")
    op.drop_column("clinics", "timezone")
    op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    clinic_plan_tier = sa.Enum("free", "practice", "clinical_pro", name="clinic_plan_tier")
    clinic_status = sa.Enum("ACTIVE", "INACTIVE", "SUSPENDED", name="clinic_status")

    clinic_status.create(op.get_bind(), checkfirst=True)

    op.create_unique_constraint(op.f("users_email_key"), "users", ["email"], postgresql_nulls_not_distinct=False)
    op.add_column("clinics", sa.Column("timezone", sa.VARCHAR(length=64), server_default=sa.text("'UTC'::character varying"), autoincrement=False, nullable=False))
    op.add_column("clinics", sa.Column("email", sa.VARCHAR(length=320), autoincrement=False, nullable=True))
    op.add_column("clinics", sa.Column("status", clinic_status, autoincrement=False, nullable=False))
    op.add_column("clinics", sa.Column("phone", sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column("clinics", sa.Column("country", sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column("clinics", sa.Column("city", sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column("clinics", sa.Column("address", sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column("clinics", sa.Column("postal_code", sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column("clinics", sa.Column("state", sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_index("ix_clinics_plan_tier", table_name="clinics")
    op.create_index(op.f("ix_clinics_status"), "clinics", ["status"], unique=False)
    op.drop_column("clinics", "is_partner_clinic")
    op.drop_column("clinics", "plan_tier")
    clinic_plan_tier.drop(op.get_bind(), checkfirst=True)
    op.drop_column("clinics", "branding_color")
    op.drop_column("clinics", "branding_logo_url")
    # ### end Alembic commands ###