"""add patient table

Revision ID: 6bb0cff00202
Revises: 8f4b2a9e1d3c
Create Date: 2026-07-22 16:53:52.103389

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '6bb0cff00202'
down_revision: str | None = '8f4b2a9e1d3c'
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_clinic_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_full_name'), table_name='patients')
    op.drop_index(op.f('ix_patients_phone'), table_name='patients')
    op.drop_index(op.f('ix_patients_status'), table_name='patients')
    op.drop_table('patients')
    op.add_column('clinics', sa.Column('branding_logo_url', sa.String(length=2048), nullable=True))
    op.add_column('clinics', sa.Column('branding_color', sa.String(length=32), nullable=True))
    op.add_column('clinics', sa.Column('plan_tier', sa.Enum('free', 'practice', 'clinical_pro', name='clinic_plan_tier'), nullable=False))
    op.add_column('clinics', sa.Column('is_partner_clinic', sa.Boolean(), nullable=False))
    op.drop_index(op.f('ix_clinics_status'), table_name='clinics')
    op.create_index('ix_clinics_plan_tier', 'clinics', ['plan_tier'], unique=False)
    op.drop_column('clinics', 'state')
    op.drop_column('clinics', 'postal_code')
    op.drop_column('clinics', 'address')
    op.drop_column('clinics', 'city')
    op.drop_column('clinics', 'country')
    op.drop_column('clinics', 'phone')
    op.drop_column('clinics', 'status')
    op.drop_column('clinics', 'email')
    op.drop_column('clinics', 'timezone')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.add_column('clinics', sa.Column('timezone', sa.VARCHAR(length=64), server_default=sa.text("'UTC'::character varying"), autoincrement=False, nullable=False))
    op.add_column('clinics', sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=True))
    op.add_column('clinics', sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', name='clinic_status'), autoincrement=False, nullable=False))
    op.add_column('clinics', sa.Column('phone', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('clinics', sa.Column('country', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('clinics', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('clinics', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('clinics', sa.Column('postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('clinics', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_index('ix_clinics_plan_tier', table_name='clinics')
    op.create_index(op.f('ix_clinics_status'), 'clinics', ['status'], unique=False)
    op.drop_column('clinics', 'is_partner_clinic')
    op.drop_column('clinics', 'plan_tier')
    op.drop_column('clinics', 'branding_color')
    op.drop_column('clinics', 'branding_logo_url')
    op.create_table('patients',
    sa.Column('clinic_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('chief_complaint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('referral_source', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'inactive', 'discharged', name='patient_status'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('patients_clinic_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('patients_pkey'))
    )
    op.create_index(op.f('ix_patients_status'), 'patients', ['status'], unique=False)
    op.create_index(op.f('ix_patients_phone'), 'patients', ['phone'], unique=False)
    op.create_index(op.f('ix_patients_full_name'), 'patients', ['full_name'], unique=False)
    op.create_index(op.f('ix_patients_clinic_id'), 'patients', ['clinic_id'], unique=False)
    # ### end Alembic commands ###