"""create patients table

Revision ID: 8f4b2a9e1d3c
Revises: 7c5d8c1b1a2f
Create Date: 2026-07-22 16:52:00.000000

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8f4b2a9e1d3c"
down_revision: str | None = "7c5d8c1b1a2f"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _ = op.create_table(
        "patients",
        sa.Column("clinic_id", sa.UUID(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("gender", sa.String(length=32), nullable=True),
        sa.Column("chief_complaint", sa.Text(), nullable=True),
        sa.Column("referral_source", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "inactive", "discharged", name="patient_status"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["clinic_id"], ["clinics.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_patients_clinic_id", "patients", ["clinic_id"], unique=False)
    op.create_index("ix_patients_full_name", "patients", ["full_name"], unique=False)
    op.create_index("ix_patients_phone", "patients", ["phone"], unique=False)
    op.create_index("ix_patients_status", "patients", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_patients_status", table_name="patients")
    op.drop_index("ix_patients_phone", table_name="patients")
    op.drop_index("ix_patients_full_name", table_name="patients")
    op.drop_index("ix_patients_clinic_id", table_name="patients")
    op.drop_table("patients")
    sa.Enum(name="patient_status").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
