"""create clinic table

Revision ID: c64933c10bdd
Revises: 
Create Date: 2026-07-21 22:13:51.080609

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'c64933c10bdd'
down_revision: str | None = None
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _ = op.create_table(
        'clinics',
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('branding_logo_url', sa.String(length=2048), nullable=True),
        sa.Column('branding_color', sa.String(length=32), nullable=True),
        sa.Column('plan_tier', sa.Enum('free', 'practice', 'clinical_pro', name='clinic_plan_tier'), nullable=False),
        sa.Column('is_partner_clinic', sa.Boolean(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clinics_name', 'clinics', ['name'], unique=False)
    op.create_index('ix_clinics_plan_tier', 'clinics', ['plan_tier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clinics_plan_tier', table_name='clinics')
    op.drop_index('ix_clinics_name', table_name='clinics')
    op.drop_table('clinics')
    # ### end Alembic commands ###