"""create treatment_sessions and soap_assessments tables

Revision ID: e1f2a3b4c5d6
Revises: d9e7c5b3a1f4
Create Date: 2026-07-22 17:37:00.000000

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "e1f2a3b4c5d6"
down_revision: str | None = "d9e7c5b3a1f4"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _ = op.create_table(
        "treatment_sessions",
        sa.Column("clinic_id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("appointment_id", sa.UUID(), nullable=True),
        sa.Column("therapist_id", sa.UUID(), nullable=False),
        sa.Column("treatment_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("pain_score", sa.Integer(), nullable=True),
        sa.Column("treatment", sa.Text(), nullable=False),
        sa.Column("home_advice", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["appointment_id"], ["appointments.id"]),
        sa.ForeignKeyConstraint(["clinic_id"], ["clinics.id"]),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"]),
        sa.ForeignKeyConstraint(["therapist_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_treatment_sessions_appointment_id", "treatment_sessions", ["appointment_id"], unique=False)
    op.create_index("ix_treatment_sessions_clinic_id", "treatment_sessions", ["clinic_id"], unique=False)
    op.create_index("ix_treatment_sessions_patient_id", "treatment_sessions", ["patient_id"], unique=False)
    op.create_index("ix_treatment_sessions_therapist_id", "treatment_sessions", ["therapist_id"], unique=False)
    op.create_index("ix_treatment_sessions_treatment_date", "treatment_sessions", ["treatment_date"], unique=False)

    _ = op.create_table(
        "soap_assessments",
        sa.Column("clinic_id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("appointment_id", sa.UUID(), nullable=True),
        sa.Column("specialty", sa.String(length=100), nullable=False),
        sa.Column("diagnosis", sa.Text(), nullable=True),
        sa.Column("is_reassessment", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("form_data", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["appointment_id"], ["appointments.id"]),
        sa.ForeignKeyConstraint(["clinic_id"], ["clinics.id"]),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_soap_assessments_appointment_id", "soap_assessments", ["appointment_id"], unique=False)
    op.create_index("ix_soap_assessments_clinic_id", "soap_assessments", ["clinic_id"], unique=False)
    op.create_index("ix_soap_assessments_patient_id", "soap_assessments", ["patient_id"], unique=False)
    op.create_index("ix_soap_assessments_specialty", "soap_assessments", ["specialty"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_soap_assessments_specialty", table_name="soap_assessments")
    op.drop_index("ix_soap_assessments_patient_id", table_name="soap_assessments")
    op.drop_index("ix_soap_assessments_clinic_id", table_name="soap_assessments")
    op.drop_index("ix_soap_assessments_appointment_id", table_name="soap_assessments")
    op.drop_table("soap_assessments")

    op.drop_index("ix_treatment_sessions_treatment_date", table_name="treatment_sessions")
    op.drop_index("ix_treatment_sessions_therapist_id", table_name="treatment_sessions")
    op.drop_index("ix_treatment_sessions_patient_id", table_name="treatment_sessions")
    op.drop_index("ix_treatment_sessions_clinic_id", table_name="treatment_sessions")
    op.drop_index("ix_treatment_sessions_appointment_id", table_name="treatment_sessions")
    op.drop_table("treatment_sessions")
    # ### end Alembic commands ###
