"""create billing tables (packages, patient_packages, invoices, invoice_items, payments)

Revision ID: f2a3b4c5d6e7
Revises: e1f2a3b4c5d6
Create Date: 2026-07-22 17:54:00.000000

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "f2a3b4c5d6e7"
down_revision: str | None = "e1f2a3b4c5d6"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None

invoice_status = postgresql.ENUM(
    "unpaid", "paid", "partial", "draft", "issued", "cancelled", "overdue",
    name="invoice_status",
    create_type=False,
)
payment_method = postgresql.ENUM(
    "cash", "upi", "card", "bank_transfer", "insurance", "other",
    name="payment_method",
    create_type=False,
)
package_status = postgresql.ENUM(
    "active", "inactive", "completed", "expired", "cancelled",
    name="package_status",
    create_type=False,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    postgresql.ENUM(
        "unpaid", "paid", "partial", "draft", "issued", "cancelled", "overdue", name="invoice_status"
    ).create(op.get_bind(), checkfirst=True)
    postgresql.ENUM(
        "cash", "upi", "card", "bank_transfer", "insurance", "other", name="payment_method"
    ).create(op.get_bind(), checkfirst=True)
    postgresql.ENUM(
        "active", "inactive", "completed", "expired", "cancelled", name="package_status"
    ).create(op.get_bind(), checkfirst=True)

    _ = op.create_table(
        "packages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clinic_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("total_sessions", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("validity_days", sa.Integer(), nullable=False),
        sa.Column("status", package_status, server_default="active", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["clinic_id"], ["clinics.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_packages_clinic_id", "packages", ["clinic_id"], unique=False)
    op.create_index("ix_packages_status", "packages", ["status"], unique=False)

    _ = op.create_table(
        "patient_packages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clinic_id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("package_id", sa.UUID(), nullable=True),
        sa.Column("package_name", sa.String(length=255), nullable=False),
        sa.Column("total_sessions", sa.Integer(), nullable=False),
        sa.Column("completed_sessions", sa.Integer(), server_default="0", nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("status", package_status, server_default="active", nullable=False),
        sa.Column("purchased_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["clinic_id"], ["clinics.id"]),
        sa.ForeignKeyConstraint(["package_id"], ["packages.id"]),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_patient_packages_clinic_id", "patient_packages", ["clinic_id"], unique=False)
    op.create_index("ix_patient_packages_patient_id", "patient_packages", ["patient_id"], unique=False)
    op.create_index("ix_patient_packages_package_id", "patient_packages", ["package_id"], unique=False)
    op.create_index("ix_patient_packages_status", "patient_packages", ["status"], unique=False)

    _ = op.create_table(
        "invoices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clinic_id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("appointment_id", sa.UUID(), nullable=True),
        sa.Column("invoice_number", sa.String(length=64), nullable=False),
        sa.Column("issue_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=10, scale=2), server_default="0.00", nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=10, scale=2), server_default="0.00", nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("paid_amount", sa.Numeric(precision=10, scale=2), server_default="0.00", nullable=False),
        sa.Column("status", invoice_status, server_default="issued", nullable=False),
        sa.Column("line_items", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["appointment_id"], ["appointments.id"]),
        sa.ForeignKeyConstraint(["clinic_id"], ["clinics.id"]),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_invoices_appointment_id", "invoices", ["appointment_id"], unique=False)
    op.create_index("ix_invoices_clinic_id", "invoices", ["clinic_id"], unique=False)
    op.create_index("ix_invoices_invoice_number", "invoices", ["invoice_number"], unique=False)
    op.create_index("ix_invoices_patient_id", "invoices", ["patient_id"], unique=False)
    op.create_index("ix_invoices_status", "invoices", ["status"], unique=False)

    _ = op.create_table(
        "invoice_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clinic_id", sa.UUID(), nullable=False),
        sa.Column("invoice_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("quantity", sa.Integer(), server_default="1", nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("total_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["clinic_id"], ["clinics.id"]),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoices.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_invoice_items_clinic_id", "invoice_items", ["clinic_id"], unique=False)
    op.create_index("ix_invoice_items_invoice_id", "invoice_items", ["invoice_id"], unique=False)

    _ = op.create_table(
        "payments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clinic_id", sa.UUID(), nullable=False),
        sa.Column("invoice_id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("payment_method", payment_method, nullable=False),
        sa.Column("payment_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("transaction_reference", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["clinic_id"], ["clinics.id"]),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoices.id"]),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_payments_clinic_id", "payments", ["clinic_id"], unique=False)
    op.create_index("ix_payments_invoice_id", "payments", ["invoice_id"], unique=False)
    op.create_index("ix_payments_patient_id", "payments", ["patient_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_payments_patient_id", table_name="payments")
    op.drop_index("ix_payments_invoice_id", table_name="payments")
    op.drop_index("ix_payments_clinic_id", table_name="payments")
    op.drop_table("payments")

    op.drop_index("ix_invoice_items_invoice_id", table_name="invoice_items")
    op.drop_index("ix_invoice_items_clinic_id", table_name="invoice_items")
    op.drop_table("invoice_items")

    op.drop_index("ix_invoices_status", table_name="invoices")
    op.drop_index("ix_invoices_patient_id", table_name="invoices")
    op.drop_index("ix_invoices_invoice_number", table_name="invoices")
    op.drop_index("ix_invoices_clinic_id", table_name="invoices")
    op.drop_index("ix_invoices_appointment_id", table_name="invoices")
    op.drop_table("invoices")

    op.drop_index("ix_patient_packages_status", table_name="patient_packages")
    op.drop_index("ix_patient_packages_package_id", table_name="patient_packages")
    op.drop_index("ix_patient_packages_patient_id", table_name="patient_packages")
    op.drop_index("ix_patient_packages_clinic_id", table_name="patient_packages")
    op.drop_table("patient_packages")

    op.drop_index("ix_packages_status", table_name="packages")
    op.drop_index("ix_packages_clinic_id", table_name="packages")
    op.drop_table("packages")

    postgresql.ENUM(name="package_status").drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name="payment_method").drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name="invoice_status").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
