"""Add Task 04 fields to prescriptions and posture

Revision ID: 074800c88a2e
Revises: 0002
Create Date: 2026-06-05 16:20:39.661480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '074800c88a2e'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posture_measurements', sa.Column('severity', sa.String(length=50), nullable=True))
    op.add_column('posture_measurements', sa.Column('visibility', sa.String(length=50), nullable=True))
    op.add_column('posture_sessions', sa.Column('overall_confidence', sa.Float(), nullable=True))
    op.add_column('posture_sessions', sa.Column('annotated_front_image', sa.String(length=255), nullable=True))
    op.add_column('posture_sessions', sa.Column('annotated_back_image', sa.String(length=255), nullable=True))
    op.add_column('posture_sessions', sa.Column('annotated_left_image', sa.String(length=255), nullable=True))
    op.add_column('posture_sessions', sa.Column('annotated_right_image', sa.String(length=255), nullable=True))
    op.add_column('prescription_items', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prescription_items', 'note')
    op.drop_column('posture_sessions', 'annotated_right_image')
    op.drop_column('posture_sessions', 'annotated_left_image')
    op.drop_column('posture_sessions', 'annotated_back_image')
    op.drop_column('posture_sessions', 'annotated_front_image')
    op.drop_column('posture_sessions', 'overall_confidence')
    op.drop_column('posture_measurements', 'visibility')
    op.drop_column('posture_measurements', 'severity')
    # ### end Alembic commands ###
