"""change branding_logo_url to Text

Revision ID: 0d063288208b
Revises: 38ebc0d87a65
Create Date: 2026-08-22 15:09:18.218714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d063288208b'
down_revision: Union[str, Sequence[str], None] = '38ebc0d87a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.
    
    NOTE: 
    Earlier: `branding_logo_url` was a VARCHAR(2048).
    Now: It is changed to TEXT.
    Why: base64-encoded image strings were exceeding the 2048 character limit, causing 422 validation errors when users tried to upload custom logos.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clinics', 'branding_logo_url',
               existing_type=sa.VARCHAR(length=2048),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clinics', 'branding_logo_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=2048),
               existing_nullable=True)
    # ### end Alembic commands ###
