"""add_crm_tables

Revision ID: 2bfb0d5801d5
Revises: b4c6f9d3e2a8
Create Date: 2026-07-23 09:25:44.809805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2bfb0d5801d5'
down_revision: Union[str, Sequence[str], None] = 'b4c6f9d3e2a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_requests',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('preferred_date', sa.Date(), nullable=True),
    sa.Column('preferred_slot', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='appointment_request_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appointment_requests_clinic_id', 'appointment_requests', ['clinic_id'], unique=False)
    op.create_index('ix_appointment_requests_phone', 'appointment_requests', ['phone'], unique=False)
    op.create_index('ix_appointment_requests_preferred_date', 'appointment_requests', ['preferred_date'], unique=False)
    op.create_index('ix_appointment_requests_status', 'appointment_requests', ['status'], unique=False)
    op.create_table('packages',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('validity_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'completed', 'expired', 'cancelled', name='package_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_packages_clinic_id', 'packages', ['clinic_id'], unique=False)
    op.create_index('ix_packages_status', 'packages', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_clinic_id', 'audit_logs', ['clinic_id'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity_type', 'audit_logs', ['entity_type'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('appointments',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('therapist_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'cancelled', 'no_show', name='appointment_status'), nullable=False),
    sa.Column('source', sa.Enum('manual', 'public_booking', name='appointment_source'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['therapist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appointments_clinic_id', 'appointments', ['clinic_id'], unique=False)
    op.create_index('ix_appointments_patient_id', 'appointments', ['patient_id'], unique=False)
    op.create_index('ix_appointments_scheduled_at', 'appointments', ['scheduled_at'], unique=False)
    op.create_index('ix_appointments_status', 'appointments', ['status'], unique=False)
    op.create_index('ix_appointments_therapist_id', 'appointments', ['therapist_id'], unique=False)
    op.create_table('leads',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('stage', sa.Enum('new', 'contacted', 'qualified', 'converted', 'lost', name='lead_stage'), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('converted_patient_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['converted_patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leads_assigned_to', 'leads', ['assigned_to'], unique=False)
    op.create_index('ix_leads_clinic_id', 'leads', ['clinic_id'], unique=False)
    op.create_index('ix_leads_converted_patient_id', 'leads', ['converted_patient_id'], unique=False)
    op.create_index('ix_leads_phone', 'leads', ['phone'], unique=False)
    op.create_index('ix_leads_stage', 'leads', ['stage'], unique=False)
    op.create_table('patient_packages',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=True),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('completed_sessions', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'inactive', 'completed', 'expired', 'cancelled', name='package_status', create_type=False), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_patient_packages_clinic_id', 'patient_packages', ['clinic_id'], unique=False)
    op.create_index('ix_patient_packages_package_id', 'patient_packages', ['package_id'], unique=False)
    op.create_index('ix_patient_packages_patient_id', 'patient_packages', ['patient_id'], unique=False)
    op.create_index('ix_patient_packages_status', 'patient_packages', ['status'], unique=False)
    op.create_table('invoices',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('invoice_number', sa.String(length=64), nullable=False),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('unpaid', 'paid', 'partial', 'draft', 'issued', 'cancelled', 'overdue', name='invoice_status'), nullable=False),
    sa.Column('line_items', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoices_appointment_id', 'invoices', ['appointment_id'], unique=False)
    op.create_index('ix_invoices_clinic_id', 'invoices', ['clinic_id'], unique=False)
    op.create_index('ix_invoices_invoice_number', 'invoices', ['invoice_number'], unique=False)
    op.create_index('ix_invoices_patient_id', 'invoices', ['patient_id'], unique=False)
    op.create_index('ix_invoices_status', 'invoices', ['status'], unique=False)
    op.create_table('soap_assessments',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('is_reassessment', sa.Boolean(), nullable=False),
    sa.Column('form_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_soap_assessments_appointment_id', 'soap_assessments', ['appointment_id'], unique=False)
    op.create_index('ix_soap_assessments_clinic_id', 'soap_assessments', ['clinic_id'], unique=False)
    op.create_index('ix_soap_assessments_patient_id', 'soap_assessments', ['patient_id'], unique=False)
    op.create_index('ix_soap_assessments_specialty', 'soap_assessments', ['specialty'], unique=False)
    op.create_table('treatment_sessions',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('therapist_id', sa.UUID(), nullable=False),
    sa.Column('treatment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pain_score', sa.Integer(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=False),
    sa.Column('home_advice', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['therapist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_treatment_sessions_appointment_id', 'treatment_sessions', ['appointment_id'], unique=False)
    op.create_index('ix_treatment_sessions_clinic_id', 'treatment_sessions', ['clinic_id'], unique=False)
    op.create_index('ix_treatment_sessions_patient_id', 'treatment_sessions', ['patient_id'], unique=False)
    op.create_index('ix_treatment_sessions_therapist_id', 'treatment_sessions', ['therapist_id'], unique=False)
    op.create_index('ix_treatment_sessions_treatment_date', 'treatment_sessions', ['treatment_date'], unique=False)
    op.create_table('invoice_items',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoice_items_clinic_id', 'invoice_items', ['clinic_id'], unique=False)
    op.create_index('ix_invoice_items_invoice_id', 'invoice_items', ['invoice_id'], unique=False)
    op.create_table('patient_documents',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('treatment_id', sa.UUID(), nullable=True),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('medical_report', 'prescription', 'lab_result', 'consent_form', 'x_ray_scan', 'id_proof', 'other', name='document_category'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatment_sessions.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_patient_documents_category', 'patient_documents', ['category'], unique=False)
    op.create_index('ix_patient_documents_clinic_id', 'patient_documents', ['clinic_id'], unique=False)
    op.create_index('ix_patient_documents_patient_id', 'patient_documents', ['patient_id'], unique=False)
    op.create_index('ix_patient_documents_treatment_id', 'patient_documents', ['treatment_id'], unique=False)
    op.create_index('ix_patient_documents_uploaded_by', 'patient_documents', ['uploaded_by'], unique=False)
    op.create_table('payments',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'upi', 'card', 'bank_transfer', 'insurance', 'other', name='payment_method'), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transaction_reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_clinic_id', 'payments', ['clinic_id'], unique=False)
    op.create_index('ix_payments_invoice_id', 'payments', ['invoice_id'], unique=False)
    op.create_index('ix_payments_patient_id', 'payments', ['patient_id'], unique=False)
    op.add_column('users', sa.Column('phone', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'phone')
    op.drop_index('ix_payments_patient_id', table_name='payments')
    op.drop_index('ix_payments_invoice_id', table_name='payments')
    op.drop_index('ix_payments_clinic_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_patient_documents_uploaded_by', table_name='patient_documents')
    op.drop_index('ix_patient_documents_treatment_id', table_name='patient_documents')
    op.drop_index('ix_patient_documents_patient_id', table_name='patient_documents')
    op.drop_index('ix_patient_documents_clinic_id', table_name='patient_documents')
    op.drop_index('ix_patient_documents_category', table_name='patient_documents')
    op.drop_table('patient_documents')
    op.drop_index('ix_invoice_items_invoice_id', table_name='invoice_items')
    op.drop_index('ix_invoice_items_clinic_id', table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index('ix_treatment_sessions_treatment_date', table_name='treatment_sessions')
    op.drop_index('ix_treatment_sessions_therapist_id', table_name='treatment_sessions')
    op.drop_index('ix_treatment_sessions_patient_id', table_name='treatment_sessions')
    op.drop_index('ix_treatment_sessions_clinic_id', table_name='treatment_sessions')
    op.drop_index('ix_treatment_sessions_appointment_id', table_name='treatment_sessions')
    op.drop_table('treatment_sessions')
    op.drop_index('ix_soap_assessments_specialty', table_name='soap_assessments')
    op.drop_index('ix_soap_assessments_patient_id', table_name='soap_assessments')
    op.drop_index('ix_soap_assessments_clinic_id', table_name='soap_assessments')
    op.drop_index('ix_soap_assessments_appointment_id', table_name='soap_assessments')
    op.drop_table('soap_assessments')
    op.drop_index('ix_invoices_status', table_name='invoices')
    op.drop_index('ix_invoices_patient_id', table_name='invoices')
    op.drop_index('ix_invoices_invoice_number', table_name='invoices')
    op.drop_index('ix_invoices_clinic_id', table_name='invoices')
    op.drop_index('ix_invoices_appointment_id', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_patient_packages_status', table_name='patient_packages')
    op.drop_index('ix_patient_packages_patient_id', table_name='patient_packages')
    op.drop_index('ix_patient_packages_package_id', table_name='patient_packages')
    op.drop_index('ix_patient_packages_clinic_id', table_name='patient_packages')
    op.drop_table('patient_packages')
    op.drop_index('ix_leads_stage', table_name='leads')
    op.drop_index('ix_leads_phone', table_name='leads')
    op.drop_index('ix_leads_converted_patient_id', table_name='leads')
    op.drop_index('ix_leads_clinic_id', table_name='leads')
    op.drop_index('ix_leads_assigned_to', table_name='leads')
    op.drop_table('leads')
    op.drop_index('ix_appointments_therapist_id', table_name='appointments')
    op.drop_index('ix_appointments_status', table_name='appointments')
    op.drop_index('ix_appointments_scheduled_at', table_name='appointments')
    op.drop_index('ix_appointments_patient_id', table_name='appointments')
    op.drop_index('ix_appointments_clinic_id', table_name='appointments')
    op.drop_table('appointments')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_type', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_clinic_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_packages_status', table_name='packages')
    op.drop_index('ix_packages_clinic_id', table_name='packages')
    op.drop_table('packages')
    op.drop_index('ix_appointment_requests_status', table_name='appointment_requests')
    op.drop_index('ix_appointment_requests_preferred_date', table_name='appointment_requests')
    op.drop_index('ix_appointment_requests_phone', table_name='appointment_requests')
    op.drop_index('ix_appointment_requests_clinic_id', table_name='appointment_requests')
    op.drop_table('appointment_requests')
    # ### end Alembic commands ###
