"""add_is_documents_enabled

Revision ID: 38ebc0d87a65
Revises: f1a2b3c4d6e7
Create Date: 2026-08-22 14:33:30.570351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38ebc0d87a65'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment_requests', 'gender',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('male', 'female', 'other', name='gender_type'),
               existing_nullable=True,
               postgresql_using='gender::gender_type')
    op.drop_column('appointment_requests', 'date_of_birth')
    op.drop_column('appointments', 'appointment_type')
    op.add_column('clinics', sa.Column('is_documents_enabled', sa.Boolean(), nullable=False))
    op.alter_column('leads', 'source',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('website', 'referral', 'social_media', 'walk_in', 'advertisement', 'other', name='lead_source_type'),
               existing_nullable=True,
               postgresql_using='source::lead_source_type')
    op.alter_column('patients', 'gender',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('male', 'female', 'other', name='gender_type'),
               existing_nullable=True,
               postgresql_using='gender::gender_type')
    op.drop_constraint(op.f('uq_payments_idempotency_key'), 'payments', type_='unique')
    op.drop_column('payments', 'status')
    op.drop_column('payments', 'idempotency_key')
    op.alter_column('soap_assessments', 'specialty',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('physiotherapy', 'chiropractic', 'osteopathy', 'massage', 'acupuncture', 'ortho', 'neuro', 'cardiopulm', 'sports', 'paeds', 'general', 'other', name='specialty_type'),
               existing_nullable=False,
               postgresql_using='specialty::specialty_type')
    op.drop_constraint(op.f('ck_users_role'), 'users', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('ck_users_role'), 'users', "role::text = ANY (ARRAY['admin'::character varying, 'therapist'::character varying, 'front_desk'::character varying]::text[])")
    op.alter_column('soap_assessments', 'specialty',
               existing_type=sa.Enum('physiotherapy', 'chiropractic', 'osteopathy', 'massage', 'acupuncture', 'ortho', 'neuro', 'cardiopulm', 'sports', 'paeds', 'general', 'other', name='specialty_type'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.add_column('payments', sa.Column('idempotency_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('status', postgresql.ENUM('pending', 'completed', 'voided', 'refunded', name='payment_status'), server_default=sa.text("'completed'::payment_status"), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_payments_idempotency_key'), 'payments', ['idempotency_key'], postgresql_nulls_not_distinct=False)
    op.alter_column('patients', 'gender',
               existing_type=sa.Enum('male', 'female', 'other', name='gender_type'),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('leads', 'source',
               existing_type=sa.Enum('website', 'referral', 'social_media', 'walk_in', 'advertisement', 'other', name='lead_source_type'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('clinics', 'is_documents_enabled')
    op.add_column('appointments', sa.Column('appointment_type', sa.VARCHAR(length=100), server_default=sa.text("'consultation'::character varying"), autoincrement=False, nullable=False))
    op.add_column('appointment_requests', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
    op.alter_column('appointment_requests', 'gender',
               existing_type=sa.Enum('male', 'female', 'other', name='gender_type'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
